name: Pages

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.3'
        id: go
      - name: dummy
        run: |
          echo "dummy"
        shell: bash
      - name: Install sg
        run: |
          go install -a github.com/ml8/sg/sg@latest
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: input
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with sg
        run: |
          sg -i input -o public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
